spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    drop-first: false

logging:
  level:
    com.together: DEBUG
    org.springframework.security: DEBUG
